packages:
  - 'packages/form'
  - 'packages/types'
  - 'packages/system'
  - 'packages/shoelace'
  - 'packages/spectrum'
  - 'packages/carbon'
  - 'packages/wired'
  - 'packages/material'
  # - 'packages/*'
